title: Opstree OSS
description: Opstree's opensource contribution to world
show_downloads: false
is_project_page: false
google_analytics:
theme: jekyll-theme-cayman
logo: opstree.png
footer_logo: static/footer-logo.png
footer_linkedin_logo: static/footer-linkedin.svg
footer_fb_logo: static/footer-fb.svg
footer_blog_logo: static/footer-blog.svg
header_page_refs: ['now', 'about', 'contact']
github_link: "https://github.com/opstree"
blog_link: "https://blog.opstree.com"
website_link: "https://opstree.com"

projects:
  - icon_path: "static/automation.svg"
    name: Automation
    description: Automation related utilities, like ansible role, scripts are present here
    subpath: /automation/
    align: left

  - icon_path: "static/containerization.svg"
    name: Container
    description: Container world related things like Kubernetes and Docker are present here
    subpath: /containerization/
    align: center

  - icon_path: "static/cloud.svg"
    name: Cloud
    description: Cloud related tools and utilities like terraform are present here
    subpath: /cloud/
    align: right

  - icon_path: "static/database.svg"
    name: Database
    description: Database related tools and utilities are present here
    subpath: /database/
    align: right

social_media:
  - name: Facebook
    icon_path: static/fb-icon.svg
    url: https://www.facebook.com/opstree

  - name: Twitter
    icon_path: static/twitter-icon.svg
    url: https://twitter.com/opstreedevops

  - name: LinkedIN
    icon_path: static/linkedin-icon.svg
    url: https://www.linkedin.com/company/opstree-solutions

  - name: GitHub
    icon_path: static/github-icon.svg
    url: https://github.com/OpsTree

  - name: Mail
    icon_path: static/mail-icon.svg
    url: mailto:connect@opstree.com

  - name: Slack
    icon_path: static/slack-icon.svg
    url: https://join.slack.com/t/opstree/shared_invite/zt-3o8jp35x-UGMU2Cy0WSBk3Lbzqa2wVw

container:
  - icon_path: "static/redis-operator.svg"
    name: Redis Operator
    description: A golang based redis operator which will make/oversee Redis setup on K8s.
    repo_link: https://github.com/OT-CONTAINER-KIT/redis-operator

  - icon_path: "static/dynamic-pv-scaler.svg"
    name: Dynamic PV Scaler
    description: A golang based K8s application which overcomes the scaling issue of PVC in K8s.
    repo_link: https://github.com/opstree/dynamic-pv-scaler

  - icon_path: "static/redis-docker-image.svg"
    name: Redis Docker Image
    description: A production based Redis and Redis Exporter docker image
    repo_link: https://github.com/OT-CONTAINER-KIT/redis

  - icon_path: "static/docker-elk.svg"
    name: Docker Compose ELK
    description: A compose setup for ELK (Elasticsearch, Logtsash and Kibana)
    repo_link: https://github.com/opstree/docker-elk

  - icon_path: "static/restic.svg"
    name: Restic Image
    description: Wrapper utility over restic for backup/restore
    repo_link: https://github.com/OT-CONTAINER-KIT/restic

  - icon_path: "static/mysql-logo.svg"
    name: MySQL Backup Image
    description: Backup utility written on top of Restic for MySQL Backup/restore
    repo_link: https://github.com/OT-CONTAINER-KIT/mysqlbackup

automation:
  - icon_path: "static/linux-logo.svg"
    name: "Ansible: Linux_armour"
    description: An ansible role to harden linux platform.
    repo_link: https://galaxy.ansible.com/opstree_devops/linux_armour

  - icon_path: "static/user-logo.svg"
    name: "Ansible: Usermanagement"
    description: An ansible role to manage users and groups on linux.
    repo_link: https://galaxy.ansible.com/opstree_devops/usermanagement

  - icon_path: "static/tomcat-logo.svg"
    name: "Ansible: Tomcat"
    description: An ansible role to install and configure Apache Tomcat.
    repo_link: https://galaxy.ansible.com/opstree_devops/tomcat

  - icon_path: "static/java-logo.svg"
    name: "Ansible: Java"
    description: An ansible role to install and configure java.
    repo_link: https://galaxy.ansible.com/opstree_devops/java

  - icon_path: "static/jenkins-logo.svg"
    name: "Ansible: Jenkins"
    description: An ansible role to install and configure jenkins server.
    repo_link: https://galaxy.ansible.com/opstree_devops/jenkins

  - icon_path: "static/kafka-logo.svg"
    name: "Ansible: Kafka"
    description: A high end ansible role which will setup kafka and zookeeper cluster.
    repo_link: https://galaxy.ansible.com/opstree_devops/kafka_cluster

  - icon_path: "static/mysql-logo.svg"
    name: "Ansible: MySQL"
    description: A high end ansible role to setup standalone or a cluster MySQL.
    repo_link: https://galaxy.ansible.com/opstree_devops/MySQL

  - icon_path: "https://upload.wikimedia.org/wikipedia/commons/f/f4/Elasticsearch_logo.svg"
    name: "Ansible: Elasticsearch"
    description: An ansible role to install and configure elasticsearch cluster.
    repo_link: https://galaxy.ansible.com/opstree_devops/elasticsearch_cluster

  - icon_path: "static/nexus-logo.svg"
    name: "Ansible: Nexus"
    description: An ansible role to install and configure Nexus.
    repo_link: https://galaxy.ansible.com/opstree_devops/nexus

  - icon_path: "static/openvpn-logo.svg"
    name: "Ansible: OpenVPN"
    description: An ansible role to install and configure OpenVPN server.
    repo_link: https://galaxy.ansible.com/opstree_devops/openvpn

  - icon_path: "static/prometheus-logo.svg"
    name: "Ansible: Prometheus"
    description: An ansible role to install and configure prometheus server.
    repo_link: https://galaxy.ansible.com/opstree_devops/prometheus

  - icon_path: "static/prometheus-logo.svg"
    name: "Ansible: Prometheus-exporters"
    description: An ansible role to install various prometheus exporters.
    repo_link: https://galaxy.ansible.com/opstree_devops/prometheus-exporters

  - icon_path: "static/alertmanager-logo.svg"
    name: "Ansible: Alertmanager"
    description: An ansible role to install and configure alertmanager server.
    repo_link: https://galaxy.ansible.com/opstree_devops/alertmanager

  - icon_path: "static/grafana-logo.svg"
    name: "Ansible: Grafana"
    description: An ansible role to install and configure grafana server.
    repo_link: https://galaxy.ansible.com/opstree_devops/grafana

  - icon_path: "https://upload.wikimedia.org/wikipedia/commons/8/82/Telegram_logo.svg"
    name: "Ansible: Sachet-telegram-integration"
    description: An ansible role to install and configure Sachet.
    repo_link: https://galaxy.ansible.com/opstree_devops/sachet-telegram-integration

database:
  - icon_path: "static/druid-exporter.svg"
    name: "Druid Exporter"
    description: A Golang based exporter to scrap druid metrics in Prometheus format.
    repo_link: https://github.com/opstree/druid-exporter

  - icon_path: "static/redis-migration.svg"
    name: "Redis Migrator"
    description: A utility to migrate redis data from one server to another
    repo_link: https://github.com/opstree/redis-migration

  - icon_path: "static/redis-load-test.svg"
    name: "Redis Load Test"
    description: A utility to test performance of Redis
    repo_link: https://github.com/opstree/redis-load-test

  - icon_path: "static/restic.svg"
    name: Restic Image
    description: Wrapper utility over restic for backup/restore
    repo_link: https://github.com/OT-CONTAINER-KIT/restic

  - icon_path: "static/mysql-logo.svg"
    name: MySQL Backup Image
    description: Backup utility written on top of Restic for MySQL Backup/restore
    repo_link: https://github.com/OT-CONTAINER-KIT/mysqlbackup

cloud:
  - icon_path: "static/cs-suite.svg"
    name: "CS Suite"
    description: Cloud Security Suite - One stop tool for auditing the security posture of AWS/GCP/Azure infrastructure.
    repo_link: https://github.com/opstree/cs-suite

  - icon_path: "static/security-group.svg"
    name: "Terraform: AWS Security Group"
    description: Terraform module which creates security group on AWS Cloud.
    repo_link: https://registry.terraform.io/modules/OT-CLOUD-KIT/security-groups/aws

  - icon_path: "static/network.svg"
    name: "Terraform: AWS Network Skeleton"
    description: Terraform module which provides networking solution on AWS Cloud.
    repo_link: https://registry.terraform.io/modules/OT-CLOUD-KIT/network-skeleton/aws

  - icon_path: "static/static-website-container.svg"
    name: "Terraform: AWS Static Website Container"
    description: Terraform module which provides static website hosting on s3 with CDN on AWS Cloud.
    repo_link: https://registry.terraform.io/modules/OT-CLOUD-KIT/static-website-container/aws

  - icon_path: "static/eks.svg"
    name: "Terraform: AWS EKS Cluster"
    description: Terraform module which creates Elastic Kubernetes service cluster on AWS Cloud.
    repo_link: https://registry.terraform.io/modules/OT-CLOUD-KIT/eks/aws

  - icon_path: "static/ha-ec2-alb.svg"
    name: "Terraform: AWS HA-EC2-ALB"
    description: Terraform module which provides a High Available and quick disaster recovery setup for EC2 in stance on AWS cloud.
    repo_link: https://registry.terraform.io/modules/OT-CLOUD-KIT/ha-ec2-alb/aws
  
  - icon_path: "static/ec2-instance.svg"
    name: "Terraform: AWS EC2 Instance"
    description: Terraform module which creates EC2 Instance on AWS Cloud.
    repo_link: https://registry.terraform.io/modules/OT-CLOUD-KIT/ec2-instance/aws

  - icon_path: "static/vpc.svg"
    name: "Terraform: AWS VPC"
    description: Terraform module which creates network skeleton on AWS Cloud.
    repo_link: https://registry.terraform.io/modules/OT-CLOUD-KIT/vpc/aws

  - icon_path: "static/route53-record-mapping.svg"
    name: "Terraform: AWS Route53 Record Mapping"
    description: Terraform module which creates Route53 Records mapping on AWS Cloud.
    repo_link: https://registry.terraform.io/modules/OT-CLOUD-KIT/route53-record-mapping/aws

  - icon_path: "static/alb-target-group.svg"
    name: "Terraform: AWS ALB Target Group"
    description: Terraform module which creates ALB target group on AWS Cloud.
    repo_link: https://registry.terraform.io/modules/OT-CLOUD-KIT/alb_target_group/aws

  - icon_path: "static/subnet.svg"
    name: "Terraform: AWS Subnet"
    description: Terraform module which creates subnets under VPC in AWS Cloud.
    repo_link: https://registry.terraform.io/modules/OT-CLOUD-KIT/subnet/aws

  - icon_path: "static/alb.svg"
    name: "Terraform: AWS ALB"
    description: Terraform module which creates ALB(Application load Balancer) with listeners in AWS Cloud.
    repo_link: https://registry.terraform.io/modules/OT-CLOUD-KIT/alb/aws
  
  - icon_path: "static/route-table.svg"
    name: "Terraform: AWS Route Table"
    description: Terraform module which creates route table on AWS Cloud.
    repo_link: https://registry.terraform.io/modules/OT-CLOUD-KIT/route-table/aws

  - icon_path: "static/nat-gateway.svg"
    name: "Terraform: AWS NAT Gateway"
    description: Terraform module which creates NAT Gateway in AWS VPC. 
    repo_link: https://registry.terraform.io/modules/OT-CLOUD-KIT/nat-gateway/aws

  - icon_path: "static/vpc-peering.svg"
    name: "Terraform: AWS VPC Peering"
    description: Terraform module which creates VPC Peering with in and cross-region in AWS Cloud. 
    repo_link: https://registry.terraform.io/modules/OT-CLOUD-KIT/vpc-peering/aws

  - icon_path: "static/elasticache-cluster.svg"
    name: "Terraform: AWS Elasticsearch Cluster"
    description: Terraform module which creates Elasticsearch Cluster in AWS Cloud. 
    repo_link: https://registry.terraform.io/modules/OT-CLOUD-KIT/elasticache-cluster/aws

  - icon_path: "static/cross-account.svg"
    name: "Terraform: AWS Cross Account Access"
    description: Terraform module which setup cross AWS account access with user specified permissions. 
    repo_link: https://registry.terraform.io/modules/OT-CLOUD-KIT/cross-account/aws

slide1_blogs:
  - blog_title: "What, Why and How of CTF Challenges?"
    blog_description: What is CTF? and how can we be part of this
    blog_link: https://blog.opstree.com/2020/02/03/what-why-and-how-of-ctf-challenges/
    published_date: Published on 3rd Feb 2020

  - blog_title: "Docker Inside Out - A Container Lifecycle"
    blog_description: Find out lifecycle of a container using Docker
    blog_link: https://blog.opstree.com/2020/01/21/docker-inside-out-a-journey-to-the-running-container/
    published_date: Published on 21st Jan 2020

  - blog_title: "Log Everything as JSON"
    blog_description: How to manage unstructured log data
    blog_link: https://blog.opstree.com/2019/12/31/log-everything-as-json/
    published_date: Published on 31st Dec 2019

  - blog_title: "Ansible Test Cases"
    blog_description: How to test ansible playbook/role using molecule with Docker
    blog_link: https://blog.opstree.com/2019/12/24/how-to-test-ansible-playbook-role-using-molecule-with-docker/
    published_date: Published on 24th Dec 2019

slide2_blogs:
  - blog_title: "Alertmanager + MS-teams"
    blog_description: How to use Alertmanager with MS-teams
    blog_link: https://blog.opstree.com/2019/12/03/prometheus-alertmanager-integration-with-ms-teams/
    published_date: Published on 3rd Dec 2019

  - blog_title: "Why GitOps is so exciting"
    blog_description: An introduction to a popular term "GitOps"
    blog_link: https://blog.opstree.com/2020/02/18/why-gitops-is-so-exciting/
    published_date: Published on 18th Feb 2020

  - blog_title: "Perfect Spot instances"
    blog_description: Incorporate and reap benifits of Spot Instances
    blog_link: https://blog.opstree.com/2019/11/05/perfect-spot-instances-imperfections-part-i/
    published_date: Published on 31st Dec 2019

  - blog_title: "Jenkins Shared Library"
    blog_description: Driver common standards and practices using Jenkins
    blog_link: https://blog.opstree.com/2019/12/24/how-to-test-ansible-playbook-role-using-molecule-with-docker/
    published_date: Published on 24th Dec 2019

latest_slide1_blogs:
  - blog_title: "Capturing Source IP in ELB and Istio's Envoy"
    blog_description: Preserve Source IP in AWS Classic Load-Balancer and Istioâ€™s envoy using proxy protocol
    blog_link: https://blog.opstree.com/2020/04/07/preserve-source-ip-in-aws-classic-load-balancer-and-istios-envoy-using-proxy-protocol/
    published_date: Published on 7th Apr 2020

  - blog_title: "Stash logs better with Logstash"
    blog_description: How to parse logs in an efficient way using logstash to reduce size of data
    blog_link: http://blog.opstree.com/2020/04/01/stash-logs-better-with-logstash/
    published_date: Published on 1st Apr 2020

  - blog_title: "Ansible directory structure (Default vs Vars)"
    blog_description: Variables behaviour in ansible and their precendence
    blog_link: http://blog.opstree.com/2020/03/24/ansible-directory-structure-default-vs-vars/
    published_date: Published on 24th Mar 2020

  - blog_title: "Terraform Workspace - Multiple Environment"
    blog_description: How to manage multiple environment infrastructure using terraform
    blog_link: http://blog.opstree.com/2020/03/18/terraform-workspace-multiple-environment/
    published_date: Published on 18th Mar 2020

latest_slide2_blogs:
  - blog_title: "Raktbeej Proxy"
    blog_description: How to manage multiple VPN connection using server, docker containers, and proxy mechanism
    blog_link: http://blog.opstree.com/2020/02/25/raktbeej-proxy/
    published_date: Published on 25th Feb 2020

  - blog_title: "Why GitOps is so exciting?"
    blog_description: Introduction to a popular term "GitOps" and how it makes life easy
    blog_link: http://blog.opstree.com/2020/04/01/stash-logs-better-with-logstash/
    published_date: Published on 18th Feb 2020

  - blog_title: "Shell initialization files"
    blog_description: Gives in-depth insights about how linux shell manage things behind the scene
    blog_link: http://blog.opstree.com/2020/02/11/shell-initialization-files/
    published_date: Published on 11th Feb 2020

  - blog_title: "What, Why and How of CTF Challanges?"
    blog_description: Introduction about CTF challanges and how you can be part of it
    blog_link: http://blog.opstree.com/2020/02/03/what-why-and-how-of-ctf-challenges/
    published_date: Published on 3rd Feb 2020
